# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 924b583824b7feffd618e7a5ef260e5b1d357f40fcab627b2e620e1dd85d161f9b61d6b078d4a209388def4515e0c44e3c97616bfc388b28e444b0885209f601

test:
  secret_key_base: 01d062c1109c1202c244ee5f0dcacc7cb25034727a68309dfa8fe966d4cda0ba3afc03c3adcf1a2f0c0bc1681b5cb226f2066e673a9ff056b164a34e8c9a9a1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
